export const FETCH_QUIZ_BY_TOKEN_REQUEST = 'player/FETCH_QUIZ_BY_TOKEN_REQUEST';
export const FETCH_QUIZ_BY_TOKEN_SUCCESS = 'player/FETCH_QUIZ_BY_TOKEN_SUCCESS';
export const FETCH_QUIZ_BY_TOKEN_FAILURE = 'player/FETCH_QUIZ_BY_TOKEN_FAILURE';

export const CREATE_PLAYER_REQUEST = 'player/CREATE_PLAYER_REQUEST';
export const CREATE_PLAYER_SUCCESS = 'player/CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILURE = 'player/CREATE_PLAYER_FAILURE';

export const ADD_PLAYER_ANSWER_REQUEST = 'player/ADD_PLAYER_ANSWER_REQUEST';
export const ADD_PLAYER_ANSWER_SUCCESS = 'player/ADD_PLAYER_ANSWER_SUCCESS';
export const ADD_PLAYER_ANSWER_FAILURE = 'player/ADD_PLAYER_ANSWER_FAILURE';

export const FINISH_PLAYER_QUIZ = 'player/FINISH_PLAYER_QUIZ';

export const SET_NEW_QUESTION = 'player/SET_NEW_QUESTION';
