export const FETCH_QUIZ_BY_TOKEN_REQUEST = 'player/FETCH_QUIZ_BY_TOKEN_REQUEST';
export const FETCH_QUIZ_BY_TOKEN_SUCCESS = 'player/FETCH_QUIZ_BY_TOKEN_SUCCESS';
export const FETCH_QUIZ_BY_TOKEN_FAILURE = 'player/FETCH_QUIZ_BY_TOKEN_FAILURE';

export const CREATE_PLAYER_REQUEST = 'player/CREATE_PLAYER_REQUEST';
export const CREATE_PLAYER_SUCCESS = 'player/CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAILURE = 'player/CREATE_PLAYER_FAILURE';



