export const CREATE_QUIZ_REQUEST = 'quiz/CREATE_QUIZ_REQUEST';
export const CREATE_QUIZ_SUCCESS = 'quiz/CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAILURE = 'quiz/CREATE_QUIZ_FAILURE';

export const DELETE_QUIZ_REQUEST = 'quiz/DELETE_QUIZ_REQUEST';
export const DELETE_QUIZ_SUCCESS = 'quiz/DELETE_QUIZ_SUCCESS';
export const DELETE_QUIZ_FAILURE = 'quiz/DELETE_QUIZ_FAILURE';

export const GET_INACTIVE_QUIZ_LIST_REQUEST = 'quiz/GET_INACTIVE_QUIZ_LIST_REQUEST';
export const GET_INACTIVE_QUIZ_LIST_SUCCESS = 'quiz/GET_INACTIVE_QUIZ_LIST_SUCCESS';
export const GET_INACTIVE_QUIZ_LIST_FAILURE = 'quiz/GET_INACTIVE_QUIZ_LIST_FAILURE';

export const GET_ACTIVE_QUIZ_LIST_REQUEST = 'quiz/GET_ACTIVE_QUIZ_LIST_REQUEST';
export const GET_ACTIVE_QUIZ_LIST_SUCCESS = 'quiz/GET_ACTIVE_QUIZ_LIST_SUCCESS';
export const GET_ACTIVE_QUIZ_LIST_FAILURE = 'quiz/GET_ACTIVE_QUIZ_LIST_FAILURE';

export const UPDATE_QUIZ_REQUEST = 'quiz/UPDATE_QUIZ_REQUEST';
export const UPDATE_QUIZ_SUCCESS = 'quiz/UPDATE_QUIZ_SUCCESS';
export const UPDATE_QUIZ_FAILURE = 'quiz/UDPATE_QUIZ_FAILURE';

export const SET_QUIZ_ACTIVE_REQUEST = 'quiz/SET_QUIZ_ACTIVE_REQUEST';
export const SET_QUIZ_ACTIVE_SUCCESS = 'quiz/SET_QUIZ_ACTIVE_SUCCESS';
export const SET_QUIZ_ACTIVE_FAILURE = 'quiz/SET_QUIZ_ACTIVE_FAILURE';

export const SET_QUIZ_FINISHED_REQUEST = 'quiz/SET_QUIZ_FINISHED_REQUEST';
export const SET_QUIZ_FINISHED_SUCCESS = 'quiz/SET_QUIZ_FINISHED_SUCCESS';
export const SET_QUIZ_FINISHED_FAILURE = 'quiz/SET_QUIZ_FINISHED_FAILURE';

export const FETCH_PLAYERS_LIST_REQUEST = 'quiz/FETCH_PLAYERS_LIST_REQUEST';
export const FETCH_PLAYERS_LIST_SUCCESS = 'quiz/FETCH_PLAYERS_LIST_SUCCESS';
export const FETCH_PLAYERS_LIST_FAILURE = 'quiz/FETCH_PLAYERS_LIST_FAILURE';

export const GET_FINISHED_QUIZ_LIST_REQUEST = 'quiz/GET_FINISHED_QUIZ_LIST_REQUEST';
export const GET_FINISHED_QUIZ_LIST_SUCCESS = 'quiz/GET_FINISHED_QUIZ_LIST_SUCCESS';
export const GET_FINISHED_QUIZ_LIST_FAILURE = 'quiz/GET_FINISHED_QUIZ_LIST_FAILURE';

export const GET_QUIZ_RESULTS_REQUEST = 'quiz/GET_QUIZ_RESULTS_REQUEST';
export const GET_QUIZ_RESULTS_SUCCESS = 'quiz/GET_QUIZ_RESULTS_SUCCESS';
export const GET_QUIZ_RESULTS_FAILURE = 'quiz/GET_QUIZ_RESULTS_FAILURE';
