export const CREATE_QUIZ_REQUEST  = 'quiz/CREATE_QUIZ_REQUEST';
export const CREATE_QUIZ_SUCCESS  = 'quiz/CREATE_QUIZ_SUCCESS';
export const CREATE_QUIZ_FAILURE  = 'quiz/CREATE_QUIZ_FAILURE';

export const GET_INACTIVE_QUIZ_LIST_REQUEST  = 'quiz/GET_INACTIVE_QUIZ_LIST_REQUEST';
export const GET_INACTIVE_QUIZ_LIST_SUCCESS  = 'quiz/GET_INACTIVE_QUIZ_LIST_SUCCESS';
export const GET_INACTIVE_QUIZ_LIST_FAILURE  = 'quiz/GET_INACTIVE_QUIZ_LIST_FAILURE';

export const GET_ACTIVE_QUIZ_LIST_REQUEST  = 'quiz/GET_ACTIVE_QUIZ_LIST_REQUEST';
export const GET_ACTIVE_QUIZ_LIST_SUCCESS  = 'quiz/GET_ACTIVE_QUIZ_LIST_SUCCESS';
export const GET_ACTIVE_QUIZ_LIST_FAILURE  = 'quiz/GET_ACTIVE_QUIZ_LIST_FAILURE';


export const UPDATE_QUIZ_REQUEST  = 'quiz/UPDATE_QUIZ_REQUEST';
export const UPDATE_QUIZ_SUCCESS  = 'quiz/UPDATE_QUIZ_SUCCESS';
export const UPDATE_QUIZ_FAILURE  = 'quiz/UDPATE_QUIZ_FAILURE';

export const SET_QUIZ_ACTIVE_REQUEST = 'quiz/SET_QUIZ_ACTIVE_REQUEST';
export const SET_QUIZ_ACTIVE_SUCCESS = 'quiz/SET_QUIZ_ACTIVE_SUCCESS';
export const SET_QUIZ_ACTIVE_FAILURE = 'quiz/SET_QUIZ_ACTIVE_FAILURE';
