export const FETCH_TOKEN_REQUEST = 'auth/FETCH_TOKEN_REQUEST';
export const FETCH_TOKEN_SUCCESS = 'auth/FETCH_TOKEN_SUCCESS';
export const FETCH_TOKEN_FAILURE = 'auth/FETCH_TOKEN_FAILURE';

export const CREATE_ACCOUNT_REQUEST = 'auth/CREATE_ACCOUNT_REQUEST';
export const CREATE_ACCOUNT_SUCCESS = 'auth/CREATE_ACCOUNT_SUCCESS';
export const CREATE_ACCOUNT_FAILURE = 'auth/CREATE_ACCOUNT_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'auth/FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'auth/FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'auth/FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'auth/RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'auth/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'auth/RESET_PASSWORD_FAILURE';

export const LOGOUT = 'auth/LOGOUT';
export const SAVE_TOKEN = 'auth/SAVE_TOKEN';
