export const CREATE_QUESTION_REQUEST = 'questions/CREATE_QUESTION_REQUEST';
export const CREATE_QUESTION_SUCCESS = 'questions/CREATE_QUESTION_SUCCESS';
export const CREATE_QUESTION_FAILURE = 'questions/CREATE_QUESTION_FAILURE';

export const DELETE_QUESTION_REQUEST = 'questions/DELETE_QUESTION_REQUEST';
export const DELETE_QUESTION_SUCCESS = 'questions/DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'questions/DELETE_QUESTION_FAILURE';

export const FETCH_QUESTIONS_LIST_REQUEST = 'questions/FETCH_QUESTIONS_LIST_REQUEST';
export const FETCH_QUESTIONS_LIST_SUCCESS = 'questions/FETCH_QUESTIONS_LIST_SUCCESS';
export const FETCH_QUESTIONS_LIST_FAILURE = 'questions/FETCH_QUESTIONS_LIST_FAILURE';

export const UPDATE_QUESTION_REQUEST = 'questions/UPDATE_QUESTION_REQUEST';
export const UPDATE_QUESTION_SUCCESS = 'questions/UPDATE_QUESTION_SUCCESS';
export const UPDATE_QUESTION_FAILURE = 'questions/UPDATE_QUESTION_FAILURE';


